### ISSUE TITLE
Export a marker type for HtmlSafeString?

### ISSUE THREAD

**Issue by rraval** [Janpot/escape-html-template-tag#7]
Hi, I see the recently released v2 has made the jump to native Typescript.

However, Typescript consumers currently need to make use of implicit `any`s for parameters and return values. Stealing an example from the README:

```ts
import html from 'escape-html-template-tag';

const list = (items) => {
    //        ^^^^^ implicitly has type `any`
    return html`
  <ul>
    ${items.map(item => html`<li>${item}</li>`)}
  </ul>
`;
};
```

It would be nice to be able to write:

```ts
import html, {HtmlSafeString} from "escape-html-template-tag";

const list = (items: Array<HtmlSafeString>) => {
    return html`
  <ul>
    ${items.map(item => html`<li>${item}</li>`)}
  </ul>
`;
};
```

Right now, callers can do something like this:

```ts
import html from 'escape-html-template-tag';

type HtmlSafeString = ReturnType<typeof html>;
```

... but that seems somewhat excessive.

---

It could be argued that `HtmlSafeString` is an implementation detail of this library and should not be exposed to allow future internal refactoring without exposing backwards incompatible details. If that's the case, then I'd suggest exposing a bare bones abstract class:

```ts
export abstract class HtmlSafeString {
    public abstract toString(): string;
}

class HtmlSafeStringImpl extends HtmlSafeString {
    // actual implementation goes here
}

// public API constructor
export default function escapeHtml (parts, ...subs) {
  return new HtmlSafeString(parts, subs)
}
```

**Comment by Janpot** [comment]
In v2.1.0 I exported the `HtmlSafeString` type. It's an implementation detail but I marked all properties as `private` so should be fine. I also touched up the types overall.
